install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion $env:APPVEYOR_BUILD_FOLDER /l console /output buildserver /updateAssemblyInfo /nofetch /b $env:APPVEYOR_REPO_BRANCH

build:
  project: Appveyor.Gitversion.sln

after_build:
  - cmd: ECHO nuget pack src\Appveyor.Gitversion.Lib\Appveyor.Gitversion.Lib.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack src\Appveyor.Gitversion.Lib\Appveyor.Gitversion.Lib.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Appveyor.Gitversion.Lib.%GitVersion_NuGetVersion%.nupkg"